# MODULES (EXTERNAL)
# ---------------------------------------------------------------------------------------------------------------------
from typing import List, Union, Dict
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.pagesizes import A4
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, 
    Table, TableStyle, ListFlowable, ListItem, 
    PageBreak
)
# ---------------------------------------------------------------------------------------------------------------------

# MODULES (INTERNAL)
# ---------------------------------------------------------------------------------------------------------------------
# Get listed here!
# ---------------------------------------------------------------------------------------------------------------------

# OPERATIONS / CLASS CREATION / GENERAL FUNCTIONS
# ---------------------------------------------------------------------------------------------------------------------

PAGE_MARGIN = 36

THEME = {
    'primary-100': colors.HexColor('#d4eaf7'),
    'primary-200': colors.HexColor('#b6ccd8'),
    'primary-300': colors.HexColor('#3b3c3d'),
    'accent-100': colors.HexColor('#71c4ef'),
    'accent-200': colors.HexColor('#00668c'),
    'text-100': colors.HexColor('#1d1c1c'),
    'text-200': colors.HexColor('#313d44'),
    'bg-100': colors.HexColor('#fffefb'),
    'bg-200': colors.HexColor('#f5f4f1'),
    'bg-300': colors.HexColor('#cccbc8')
}

FONT_STYLE = 'Helvetica'
FONT_STYLE_BOLD = 'Helvetica-Bold'

title_h0 = ParagraphStyle(
    'TitleH0',
    fontName=FONT_STYLE_BOLD,
    fontSize=24,
    alignment=TA_CENTER,
    textColor=THEME['text-100'],
    spaceAfter=25
)
title_h1 = ParagraphStyle(
    'TitleH1',
    fontName=FONT_STYLE_BOLD,
    fontSize=20,
    alignment=TA_JUSTIFY,
    textColor=THEME['text-100']
)
title_h2 = ParagraphStyle(
    'TitleH2',
    fontName=FONT_STYLE_BOLD,
    fontSize=16,
    alignment=TA_JUSTIFY,
    textColor=THEME['text-100']
)
title_h3 = ParagraphStyle(
    'TitleH3',
    fontName=FONT_STYLE_BOLD,
    fontSize=14,
    alignment=TA_JUSTIFY,
    textColor=THEME['text-100']
)
title_h4 = ParagraphStyle(
    'TitleH4',
    fontName=FONT_STYLE_BOLD,
    fontSize=12,
    alignment=TA_JUSTIFY,
    textColor=THEME['text-100']
)
footer = ParagraphStyle(
    'Footer',
    fontName=FONT_STYLE,
    fontSize=11,
    alignment=TA_CENTER,
    textColor=THEME['text-100'],
    spaceBefore=10
)
paragraph_style = ParagraphStyle(
    'ParagraphStyle',
    fontName=FONT_STYLE,
    fontSize=11,
    alignment=TA_JUSTIFY,
    textColor=THEME['text-100']
)

class Document:
    """
    
    """

    def __init__(self, filename: str) -> None:
        self.__story = []
        self.__doc = SimpleDocTemplate(
            filename,
            pagesize=A4,
            leftMargin=PAGE_MARGIN,
            rightMargin=PAGE_MARGIN,
            topMargin=PAGE_MARGIN,
            bottomMargin=PAGE_MARGIN
        )

    def build(self) -> None:
        """
        
        """
        self.__doc.build(self.__story)

    def front_page(self, repository_name: str, analysis_date: str, version: str) -> None:
        """
        
        """
        # Main title
        self.__story.append(Spacer(1, 20))
        self.__story.append(Paragraph('TECHNICAL REPOSITORY', title_h0))
        self.__story.append(Paragraph('ANALYSIS REPORT', title_h0))

        # Repository name
        self.__story.append(Spacer(1, 240))
        self.__story.append(Paragraph('Repository analyzed:', title_h0))
        self.__story.append(Paragraph(repository_name, title_h0))
        self.__story.append(Spacer(1, 300))

        # Footer near bottom
        self.__story.append(Paragraph(analysis_date, footer))
        self.__story.append(Paragraph(f'Report generated by Codemnesis - v.{version}', footer))

        self.__story.append(PageBreak())

    def summary_page(self, summary: Dict[str, Union[str, List[str]]]) -> None:
        """
        
        """
        self.__story.append(Paragraph('Executive summary', title_h1))

# ---------------------------------------------------------------------------------------------------------------------
# END OF FILE